use Test


CREATE TABLE CUSTOMERS (
	ID INT PRIMARY KEY,
	NAME VARCHAR(50),
	AGE INT,
	ADDRESS CHAR(50),
	SALAY DECIMAL (18, 2)
);

SELECT * FROM CUSTOMERS

INSERT INTO CUSTOMERS VALUES
(1, 'Ramesh', 32, 'Ahmedabad', 2000.00),
(2, 'Khilan', 25, 'Delhi', 1500.00),
(3, 'Kaushik', 23, 'Kota', 2000.00),
(4, 'Chaitali', 25, 'Mumbai', 6500.00),
(5, 'Hardik', 27, 'Bhopal', 8500.00),
(6, 'Komal', 22, 'Hyderabad', 4500.00),
(7, 'Muffy', 24, 'Indore', 10000.00);

ALTER TABLE CUSTOMERS ADD SALARY DECIMAL(18, 2)
UPDATE CUSTOMERS SET SALARY = SALAY
ALTER TABLE CUSTOMERS DROP COLUMN SALAY

---USING WHERE CLAUSE---
SELECT ID, NAME, SALARY FROM CUSTOMERS
WHERE SALARY > 2000

--- WHERE CLAUSE WITH UPDATE STATEMENT---
UPDATE CUSTOMERS SET SALARY = SALARY + 1000
WHERE NAME = 'Ramesh'

--- WHERE CLUSE WITH IN KEY WORD ---
SELECT * FROM CUSTOMERS
WHERE ADDRESS IN ('Bhopal', 'Ahmedabad')

---WHERE CLAUSE WITH NOT IN STAEMENT---
SELECT * FROM CUSTOMERS
WHERE AGE NOT IN(25, 23,22)

---WHERE CLAUSE WITH LIKE STATEMENT---
SELECT * FROM CUSTOMERS
WHERE NAME LIKE 'H____%'

---WHERE CLAUSE WITH AND / OR OPERATOR ---
SELECT * FROM CUSTOMERS
WHERE(AGE < 25 OR NAME ='Ramesh') AND SALARY > 2000

--- TOP CLUSE ---
SELECT TOP 3 * FROM CUSTOMERS 

--- TOP CLAUSE WITH ORDER BY ---
SELECT TOP 3 * FROM CUSTOMERS ORDER BY SALARY DESC

--- ORDER BY CLAUSE ---

SELECT TOP 3 * FROM CUSTOMERS ORDER BY SALARY ASC
SELECT * FROM CUSTOMERS ORDER BY SALARY DESC

--TO PRINT THE 2ND LARGEST VALUE OF A TABLE--
SELECT TOP 1 * FROM
(
	SELECT DISTINCT TOP 2 * FROM CUSTOMERS
	ORDER BY SALARY DESC
) AS TEMP
ORDER BY SALARY ASC

--- GROUP BY CLAUSE ---
SELECT AGE, COUNT(NAME) FROM CUSTOMERS GROUP BY AGE

SELECT AGE, MAX(SALARY) AS MAX_SALARY
FROM CUSTOMERS GROUP BY AGE

SELECT ADDRESS, AVG(SALARY) AS AVG_SALARY
FROM CUSTOMERS GROUP BY ADDRESS

SELECT AGE, MIN(SALARY) AS MIN_SALARY 
FROM CUSTOMERS
GROUP BY AGE ORDER BY MIN_SALARY DESC

SELECT ADDRESS, AGE, MIN(SALARY) AS MIN_SALARY
FROM CUSTOMERS
GROUP BY ADDRESS, AGE HAVING AGE > 24

SELECT ADDRESS, AGE, SUM(SALARY) AS TOTAL_SALARY 
FROM CUSTOMERS 
GROUP BY ADDRESS, AGE HAVING SUM(SALARY) >=5000 
ORDER BY SUM(SALARY) DESC;

SELECT ADDRESS,MAX(SALARY) AS MAX_SALARY
FROM CUSTOMERS
GROUP BY ADDRESS, SALARY HAVING MAX(SALARY) > 5000

CREATE TABLE ORDERS
(
	OID INT PRIMARY KEY NOT NULL,
	DATE VARCHAR(20),
	CUSTOMER_ID INT NOT NULL,
	AMOUNT DECIMAL(18, 2)
)

INSERT INTO ORDERS VALUES 
(102, '2009-10-08 00:00:00', 3, 3000.00),
(100, '2009-10-08 00:00:00', 3, 1500.00),
(101, '2009-11-20 00:00:00', 2, 1560.00),
(103, '2008-05-20 00:00:00', 4, 2060.00);

--- SIMPLE JOIN OPERATION ---
SELECT ID, NAME, AGE, AMOUNT
FROM CUSTOMERS
JOIN ORDERS
ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID



CREATE TABLE EMPLOYEE (
   EID INT NOT NULL,
   EMPLOYEE_NAME VARCHAR (30) NOT NULL,
   SALES_MADE DECIMAL (20)
);
INSERT INTO EMPLOYEE VALUES
(102, 'SARIKA', 4500),
(100, 'ALEKHYA', 3623),
(101, 'REVATHI', 1291),
(103, 'VIVEK', 3426);

SELECT * FROM EMPLOYEE

--- INNER JOIN ---
SELECT OID, DATE, AMOUNT, EMPLOYEE_NAME 
FROM CUSTOMERS
INNER JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID
INNER JOIN EMPLOYEE ON ORDERS.OID = EMPLOYEE.EID

--- INNER JOIN WITH WHERE CLAUSE ---
SELECT ID, NAME, DATE, AMOUNT FROM CUSTOMERS
INNER JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID
WHERE ORDERS.AMOUNT > 2500

--- LEFT JOIN ---
SELECT CUSTOMERS.ID, CUSTOMERS.NAME, ORDERS.DATE, EMPLOYEE.EMPLOYEE_NAME
FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID
LEFT JOIN EMPLOYEE ON ORDERS.OID = EMPLOYEE.EID


--- LEFT JOIN WITH WHERE CLAUSE ---
SELECT CUSTOMERS.NAME, ORDERS.AMOUNT, EMPLOYEE.EMPLOYEE_NAME, ORDERS.AMOUNT
FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID
LEFT JOIN EMPLOYEE ON ORDERS.OID = EMPLOYEE.EID
WHERE ORDERS.AMOUNT > 2000


--- TRIGGER ---
ALTER TABLE EMPLOYEE
ADD YEARLY_SALARY DECIMAL(20, 2)

SELECT * FROM EMPLOYEE

UPDATE EMPLOYEE
SET YEARLY_SALARY = SALES_MADE * 12



CREATE TRIGGER trg_UpdateYearlySalary
ON EMPLOYEE
AFTER UPDATEs
AS
BEGIN
    UPDATE EMPLOYEE
    SET YEARLY_SALARY = i.SALES_MADE * 12
    FROM inserted i
    WHERE EMPLOYEE.EID = i.EID;
END;
GO


UPDATE EMPLOYEE
SET SALES_MADE = 10
WHERE EID = 100
